// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpwy09wMlPh5_PXiNO15C5IlD2M5HnRYc',
    appId: '1:910999530990:web:7ef6a11a9742932cd2f2ff',
    messagingSenderId: '910999530990',
    projectId: 'talk-pro-d9726',
    authDomain: 'talk-pro-d9726.firebaseapp.com',
    storageBucket: 'talk-pro-d9726.appspot.com',
    measurementId: 'G-8398NPDEGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChdOIFjtltUhrvDAK7piP8pFc353VNC7A',
    appId: '1:910999530990:android:90cf93d17eeea467d2f2ff',
    messagingSenderId: '910999530990',
    projectId: 'talk-pro-d9726',
    storageBucket: 'talk-pro-d9726.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAskOqx4JxJESdUjrlUGeiyfzGHFShEtMY',
    appId: '1:910999530990:ios:4cfeacc21862da55d2f2ff',
    messagingSenderId: '910999530990',
    projectId: 'talk-pro-d9726',
    storageBucket: 'talk-pro-d9726.appspot.com',
    iosBundleId: 'com.example.talkPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAskOqx4JxJESdUjrlUGeiyfzGHFShEtMY',
    appId: '1:910999530990:ios:67651f4d947a8d61d2f2ff',
    messagingSenderId: '910999530990',
    projectId: 'talk-pro-d9726',
    storageBucket: 'talk-pro-d9726.appspot.com',
    iosBundleId: 'com.example.talkPro.RunnerTests',
  );
}
